import type { Bill, BillsResponse, ScrapeJob } from '../types';

export const mockJurisdictions: string[] = [
  'congress.gov',
  'federalregister.gov',
  'leginfo.legislature.ca.gov',
  'le.utah.gov',
];

export const mockBills: Bill[] = [
  {
    id: 1001,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/1234',
    search_term: '"AI Bill" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:30:00Z',
    excerpt:
      'A bill to establish transparency requirements for automated decision systems used by federal agencies...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1002,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/5678',
    search_term: '"Algorithmic accountability" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:28:00Z',
    excerpt:
      'A bill to require algorithmic impact assessments before deployment of high-risk AI systems...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1003,
    source_url: 'https://www.federalregister.gov/documents/2026/01/15/2026-00123/example-ai-rulemaking',
    search_term: '"AI rulemaking" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:21:00Z',
    excerpt:
      'The agency requests public comment on proposed guidance for use of AI in administrative adjudication...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1004,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/2201',
    search_term: '"AI safety" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:27:00Z',
    excerpt:
      'A bill to create a federal AI Safety Board responsible for evaluating existential and systemic risks posed by advanced artificial intelligence systems...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1005,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/3310',
    search_term: '"machine learning" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:26:00Z',
    excerpt:
      'A bill to require federal contractors to disclose use of machine learning models in procurement decisions and to conduct bias audits annually...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1006,
    source_url: 'https://www.federalregister.gov/documents/2026/02/03/2026-00456/ai-procurement-guidance',
    search_term: '"artificial intelligence" site:federalregister.gov inurl:/documents',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:25:00Z',
    excerpt:
      'Proposed rule establishing minimum standards for AI system procurement by executive branch agencies, including documentation and auditability requirements...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1007,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/4402',
    search_term: '"deepfake" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:24:00Z',
    excerpt:
      'A bill to prohibit the creation and distribution of nonconsensual synthetic media depicting real individuals without explicit disclosure and consent...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1008,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/7891',
    search_term: '"generative AI" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:23:00Z',
    excerpt:
      'A bill to establish labeling requirements for content generated by artificial intelligence systems distributed through online platforms...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1009,
    source_url: 'https://www.federalregister.gov/documents/2026/02/18/2026-00789/automated-benefits-determination',
    search_term: '"automated decision" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:22:00Z',
    excerpt:
      'Notice of proposed rulemaking to govern use of automated systems in federal benefits eligibility determinations, including right-to-explanation provisions...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1010,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/5530',
    search_term: '"facial recognition" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:20:00Z',
    excerpt:
      'A bill to impose a moratorium on federal law enforcement use of facial recognition technology pending independent accuracy and civil liberties review...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1011,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/1122',
    search_term: '"AI liability" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:19:00Z',
    excerpt:
      'A bill to establish a strict liability framework for harms caused by high-risk autonomous AI systems deployed in critical infrastructure...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1012,
    source_url: 'https://www.federalregister.gov/documents/2026/03/01/2026-01011/national-ai-research-cloud',
    search_term: '"AI research" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:18:00Z',
    excerpt:
      'Final rule establishing the National AI Research Cloud program, providing computational resources to academic and nonprofit researchers for AI safety studies...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1013,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/6644',
    search_term: '"algorithmic bias" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:17:00Z',
    excerpt:
      'A bill to prohibit the use of biased algorithmic systems in housing, lending, and employment decisions and to establish a federal audit registry...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1014,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/2233',
    search_term: '"AI in healthcare" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:16:00Z',
    excerpt:
      'A bill to regulate artificial intelligence systems used in clinical decision support, requiring FDA clearance and post-market surveillance protocols...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1015,
    source_url: 'https://www.federalregister.gov/documents/2026/03/10/2026-01234/export-controls-ai-chips',
    search_term: '"AI export controls" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:15:00Z',
    excerpt:
      'Interim final rule expanding export control classifications for advanced AI accelerator chips and model weights to additional foreign jurisdictions...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1016,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/7755',
    search_term: '"autonomous vehicles" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:14:00Z',
    excerpt:
      'A bill to establish a unified federal framework for the testing, certification, and deployment of autonomous vehicle systems on public roads...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1017,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/3344',
    search_term: '"AI workforce" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:13:00Z',
    excerpt:
      'A bill to establish worker transition assistance programs and retraining grants for employees displaced by AI-driven automation in manufacturing and services sectors...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1018,
    source_url: 'https://www.federalregister.gov/documents/2026/03/22/2026-01567/ai-cybersecurity-standards',
    search_term: '"AI cybersecurity" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:12:00Z',
    excerpt:
      'NIST requests comment on draft cybersecurity standards specific to AI systems, covering adversarial robustness, data poisoning protections, and incident response...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1019,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/8866',
    search_term: '"AI transparency" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:11:00Z',
    excerpt:
      'A bill to mandate public disclosure of training datasets, model architecture, and intended use cases for AI systems deployed by or sold to federal agencies...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1020,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/4455',
    search_term: '"children AI privacy" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:10:00Z',
    excerpt:
      'A bill to prohibit AI-powered data collection and behavioral profiling targeting individuals under the age of 18 on digital platforms...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1021,
    source_url: 'https://www.federalregister.gov/documents/2026/04/01/2026-01890/foundation-model-reporting',
    search_term: '"foundation model" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:09:00Z',
    excerpt:
      'Proposed rule requiring developers of foundation models above a specified compute threshold to file safety evaluations and capability reports with NIST prior to release...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1022,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/9977',
    search_term: '"AI national security" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:08:00Z',
    excerpt:
      'A bill to restrict the acquisition of AI systems developed by entities in foreign adversary nations for use in national security or defense applications...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1023,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/5566',
    search_term: '"AI education" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:07:00Z',
    excerpt:
      'A bill to integrate AI literacy and digital ethics into K–12 national education standards and to fund teacher training programs across underserved school districts...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1024,
    source_url: 'https://www.federalregister.gov/documents/2026/04/08/2026-02013/ai-environmental-impact',
    search_term: '"AI energy use" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:06:00Z',
    excerpt:
      'EPA proposes environmental reporting requirements for large-scale AI data centers, including energy consumption disclosures, water usage, and carbon offset plans...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1025,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/1100',
    search_term: '"predictive policing" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:05:00Z',
    excerpt:
      'A bill to ban federal funding for predictive policing software and to require jurisdictions currently using such tools to conduct civil rights impact assessments...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1026,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/6677',
    search_term: '"AI in financial services" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:04:00Z',
    excerpt:
      'A bill to require financial institutions to disclose AI use in credit scoring, fraud detection, and investment advice and to establish a consumer right to human review...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1027,
    source_url: 'https://www.federalregister.gov/documents/2026/04/15/2026-02234/dod-autonomous-weapons-policy',
    search_term: '"autonomous weapons" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:03:00Z',
    excerpt:
      'Department of Defense publishes updated directive requiring meaningful human control over lethal autonomous weapon systems and establishing review boards for AI-enabled targeting...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1028,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/2211',
    search_term: '"AI copyright" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:02:00Z',
    excerpt:
      'A bill to clarify copyright protections for AI-generated works, establishing authorship attribution rules and opt-out mechanisms for training data use...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1029,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/7788',
    search_term: '"AI hiring" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T10:01:00Z',
    excerpt:
      'A bill to require employers using AI tools in hiring to notify applicants, disclose evaluation criteria, and submit to annual third-party bias audits...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1030,
    source_url: 'https://www.federalregister.gov/documents/2026/04/20/2026-02456/ai-risk-management-framework',
    search_term: '"AI risk management" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T10:00:00Z',
    excerpt:
      'NIST releases final version of AI Risk Management Framework 2.0, incorporating updates on generative AI governance, red-teaming protocols, and third-party auditing standards...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1031,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/3322',
    search_term: '"open source AI" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:59:00Z',
    excerpt:
      'A bill to promote open-source AI development by federal agencies and to establish a public model repository maintained by the National Science Foundation...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1032,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/8899',
    search_term: '"AI surveillance" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:58:00Z',
    excerpt:
      'A bill to prohibit federal agencies from using AI-powered mass surveillance tools without individualized warrants and independent judicial oversight...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1033,
    source_url: 'https://www.federalregister.gov/documents/2026/04/28/2026-02678/ai-clinical-trials-guidance',
    search_term: '"AI clinical trials" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T09:57:00Z',
    excerpt:
      'FDA guidance document on use of AI and machine learning in the design and analysis of clinical trials, covering adaptive trial protocols and real-world evidence generation...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1034,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/4433',
    search_term: '"AI accountability" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:56:00Z',
    excerpt:
      'A bill to create an independent AI Accountability Office within the legislative branch to evaluate AI systems used by executive agencies and issue public findings...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1035,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/9900',
    search_term: '"AI small business" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:55:00Z',
    excerpt:
      'A bill to authorize SBA grants and technical assistance programs to help small businesses adopt AI tools while complying with emerging federal regulatory requirements...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1036,
    source_url: 'https://www.federalregister.gov/documents/2026/05/02/2026-02901/ai-immigration-enforcement',
    search_term: '"AI immigration" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T09:54:00Z',
    excerpt:
      'DHS proposes rules governing use of AI tools in immigration enforcement actions, including due process requirements and mandatory human review for deportation recommendations...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1037,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/5544',
    search_term: '"AI mental health" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:53:00Z',
    excerpt:
      'A bill to regulate AI-powered mental health applications, requiring clinical validation, data privacy protections, and mandatory referrals to licensed practitioners in crisis scenarios...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1038,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/1234',
    search_term: '"AI elections" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:52:00Z',
    excerpt:
      'A bill to require disclosure of AI-generated content in political advertising and to prohibit synthetic media designed to fraudulently impersonate candidates or election officials...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1039,
    source_url: 'https://www.federalregister.gov/documents/2026/05/05/2026-03123/ai-financial-stability',
    search_term: '"AI financial stability" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T09:51:00Z',
    excerpt:
      'Financial Stability Oversight Council report on systemic risks posed by widespread AI adoption in financial markets, including recommendations for stress-testing and oversight protocols...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1040,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/6655',
    search_term: '"AI grid infrastructure" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:50:00Z',
    excerpt:
      'A bill to authorize federal investment in AI-powered smart grid technologies while establishing cybersecurity requirements to protect critical energy infrastructure...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1041,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/2345',
    search_term: '"AI drug discovery" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:49:00Z',
    excerpt:
      'A bill to create a regulatory pathway for AI-designed therapeutics and to establish NIH grants for AI-assisted drug discovery targeting rare and neglected diseases...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1042,
    source_url: 'https://www.federalregister.gov/documents/2026/05/08/2026-03345/ai-content-moderation-standards',
    search_term: '"AI content moderation" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T09:48:00Z',
    excerpt:
      'FTC proposes standards for AI-based content moderation systems, including transparency reporting, appeals mechanisms, and accuracy benchmarks for prohibited content detection...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1043,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/7766',
    search_term: '"AI agriculture" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:47:00Z',
    excerpt:
      'A bill to fund USDA programs supporting AI-enabled precision agriculture technology adoption among family farms and to develop voluntary data-sharing standards for crop AI systems...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1044,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/3456',
    search_term: '"biometric data AI" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:46:00Z',
    excerpt:
      'A bill to restrict the commercial collection and sale of biometric data for AI training purposes without informed, affirmative consent from individuals...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1045,
    source_url: 'https://www.federalregister.gov/documents/2026/05/10/2026-03567/ai-criminal-justice-use',
    search_term: '"AI criminal justice" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T09:45:00Z',
    excerpt:
      'DOJ issues guidance on permissible uses of AI tools in federal criminal proceedings, including evidentiary standards for AI-generated forensic evidence and discovery obligations...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1046,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/8877',
    search_term: '"AI competition" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:44:00Z',
    excerpt:
      'A bill to direct the FTC to investigate and address anticompetitive practices in the AI foundation model market, including exclusive cloud compute partnerships and data moats...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1047,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/4567',
    search_term: '"AI climate" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:43:00Z',
    excerpt:
      'A bill to authorize NOAA and DOE to deploy AI systems for climate modeling, carbon capture optimization, and disaster response prediction, with open-access data requirements...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1048,
    source_url: 'https://www.federalregister.gov/documents/2026/05/12/2026-03789/ai-federal-workforce-guidance',
    search_term: '"AI federal workforce" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T09:42:00Z',
    excerpt:
      'OPM guidance on acceptable use of generative AI tools by federal employees, covering data handling, output review requirements, prohibited use cases, and mandatory training standards...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1049,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/9988',
    search_term: '"AI veterans benefits" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:41:00Z',
    excerpt:
      'A bill to require VA to notify veterans when AI tools are used in benefits claims adjudication and to guarantee the right to a human case review upon request...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1050,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/5678',
    search_term: '"AI research funding" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:40:00Z',
    excerpt:
      'A bill to authorize $10 billion over five years for NSF, DARPA, and DOE to fund basic and applied AI research with a focus on safety, interpretability, and societal impact...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1051,
    source_url: 'https://www.federalregister.gov/documents/2026/05/14/2026-04012/ai-housing-discrimination',
    search_term: '"AI housing discrimination" site:federalregister.gov',
    domain: 'federalregister.gov',
    created_at: '2026-05-19T09:39:00Z',
    excerpt:
      'HUD proposes enforcement guidance clarifying that discriminatory outputs of AI-driven tenant screening and mortgage underwriting tools constitute violations of the Fair Housing Act...',
    text_processing_method: 'Federal Register API',
  },
  {
    id: 1052,
    source_url: 'https://www.congress.gov/bill/118th-congress/house-bill/1011',
    search_term: '"AI international standards" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:38:00Z',
    excerpt:
      'A bill to direct the State Department to negotiate bilateral and multilateral AI governance agreements and to represent U.S. interests in international AI standards bodies...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
  {
    id: 1053,
    source_url: 'https://www.congress.gov/bill/118th-congress/senate-bill/6789',
    search_term: '"AI whistleblower" site:congress.gov inurl:/bill',
    domain: 'congress.gov',
    created_at: '2026-05-19T09:37:00Z',
    excerpt:
      'A bill to extend federal whistleblower protections to employees of AI companies who report unsafe practices, deceptive capability claims, or civil rights violations to federal authorities...',
    text_processing_method: 'Congress.gov API (HTM)',
  },
];

export const mockBillsResponse: BillsResponse = {
  bills: mockBills,
  total: mockBills.length,
  page: 1,
  per_page: 20,
  total_pages: 1,
};

export const mockBillById: Record<number, Bill> = Object.fromEntries(
  mockBills.map((bill) => [bill.id, bill]),
);

export const mockJobRunning: ScrapeJob = {
  job_id: 'mock-job-running',
  status: 'running',
  runtime_seconds: 98,
  log_size_bytes: 3221,
  last_log_update_seconds_ago: 4,
  activity_state: 'active',
  config: {
    terms: ['AI Bill', 'Algorithmic accountability'],
    jurisdictions: {
      'congress.gov': { signals: ['/bill'] },
      'federalregister.gov': {},
    },
    start_date: '2026-01-01',
    end_date: '2026-05-01',
  },
};

export const mockJobCompleted: ScrapeJob = {
  job_id: 'mock-job-completed',
  status: 'completed',
  config: {
    terms: ['AI Bill', 'Algorithmic accountability'],
    jurisdictions: {
      'congress.gov': { signals: ['/bill'] },
      'federalregister.gov': {},
    },
    start_date: '2026-01-01',
    end_date: '2026-05-01',
  },
  results: {
    total_URLs: 7,
    successful_URLs: 5,
    failed_URLs: 2,
    processed_urls: [
      {
        url: 'https://www.congress.gov/bill/118th-congress/house-bill/1234',
        success: true,
      },
      {
        url: 'https://www.congress.gov/bill/118th-congress/senate-bill/5678',
        success: true,
      },
      {
        url: 'https://www.federalregister.gov/documents/2026/01/15/2026-00123/example-ai-rulemaking',
        success: true,
      },
      {
        url: 'https://www.congress.gov/bill/118th-congress/house-bill/9012',
        success: false,
        error: 'Failed to retrieve HTML after retries',
      },
    ],
    scheduled: {
      new_urls_found: 3,
      urls_fixed: 2,
    },
  },
};

export const mockJobFailed: ScrapeJob = {
  job_id: 'mock-job-failed',
  status: 'failed',
  config: {
    terms: ['AI Bill'],
    jurisdictions: {
      'congress.gov': { signals: ['/bill'] },
    },
  },
  log: 'FATAL ERROR: Mocked backend failure while processing batch 3',
};

export const mockScrapeJobs: ScrapeJob[] = [
  mockJobRunning,
  mockJobCompleted,
  mockJobFailed,
];
